### PR TITLE
Update docs/tutorials/compile-the-guardrail-script.mdx

### PR DESCRIPTION
**Pull request by bezirg**

### CODE REVIEW

**Comment by bezirg** [comment]
@CarlosLopezDeLara @perturbing

**Comment by CarlosLopezDeLara** [comment]
The resulting script hash is 

```
cardano-cli hash script --script-file guardrail-clrtest.plutus
a62f234916a9633a7831f16f2b7e4c465261b300a00296b2ee66f3c2
```
I was expecting `fa24fb305126805cf2164c161d852a0e7330cf988f1fe558cf7d4a64`
as in https://book.world.dev.cardano.org/environments/mainnet/conway-genesis.json

So if I was to submit a governance action with `guardrail-clrtest.plutus` it would fail. 

```
plutus on  HEAD (200ad0f) [$!?] via λ 9.6.6 via ❄️  impure (ghc-shell-for-packages-env) took 6s 
❯ cabal --version 
cabal-install version 3.12.1.0
compiled using version 3.12.1.0 of the Cabal library 

plutus on  HEAD (200ad0f) [$!?] via λ 9.6.6 via ❄️  impure (ghc-shell-for-packages-env) 
❯ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.6.6
```

**Comment by bezirg** [comment]
This can happen because the compiler has changed since version 1.31.0.0 , so the uplc output may have changed as well.

**Comment by bezirg** [comment]
Then shall I close this PR? It does not make sense anymore, since we are fixed into a script compiled using a specific plutus-compiler version

**Comment by CarlosLopezDeLara** [comment]
Is there a way out to simplify the compilation method while ensuring we get the same script hash?  If not, we will need to stick to current instructions by @perturbing

**Comment by perturbing** [comment]
I'm still building, but that is what I expected to happen as well, as I already built another version and particularly had to make the tutorial to match the hash

**Comment by perturbing** [comment]
I am also getting the hash `a62f234916a9633a7831f16f2b7e4c465261b300a00296b2ee66f3c2` :/ 

I think the aim of this tutorial is to prove that the mainnet script is really the result of the old tutorial, so let's close the PR :)

**Pull request closed without merging**
